Ac/config/routes.rb
Rails.application.routes.draw do
  resources :geocoders
  root "rooms#show"
mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Ac/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Ac/app/models/geocoder.rb
class Geocoder < ApplicationRecord
  
  attr_accessible :address,:latitude,:longitude
   geocoded_by :address 
   after_validation :geocode 
end

Ac/app/models/message.rb
class Message < ApplicationRecord
	after_create_commit {MessageBrodcastJob.perform_later self}
end

Ac/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Ac/app/controllers/geocoders_controller.rb
class GeocodersController < ApplicationController
  before_action :set_geocoder, only: [:show, :edit, :update, :destroy]

  # GET /geocoders
  # GET /geocoders.json
  def index
    @geocoders = Geocoder.all
  end

  # GET /geocoders/1
  # GET /geocoders/1.json
  def show
  end

  # GET /geocoders/new
  def new
    @geocoder = Geocoder.new
  end

  # GET /geocoders/1/edit
  def edit
  end

  # POST /geocoders
  # POST /geocoders.json
  def create
    @geocoder = Geocoder.new(geocoder_params)

    respond_to do |format|
      if @geocoder.save
        format.html { redirect_to @geocoder, notice: 'Geocoder was successfully created.' }
        format.json { render :show, status: :created, location: @geocoder }
      else
        format.html { render :new }
        format.json { render json: @geocoder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /geocoders/1
  # PATCH/PUT /geocoders/1.json
  def update
    respond_to do |format|
      if @geocoder.update(geocoder_params)
        format.html { redirect_to @geocoder, notice: 'Geocoder was successfully updated.' }
        format.json { render :show, status: :ok, location: @geocoder }
      else
        format.html { render :edit }
        format.json { render json: @geocoder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /geocoders/1
  # DELETE /geocoders/1.json
  def destroy
    @geocoder.destroy
    respond_to do |format|
      format.html { redirect_to geocoders_url, notice: 'Geocoder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_geocoder
      @geocoder = Geocoder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def geocoder_params
      params.require(:geocoder).permit(:address, :latitude, :longitude)
    end
end

Ac/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
  	@messages = Message.all
  end
end

Ac/app/helpers/application_helper.rb
module ApplicationHelper
end

Ac/app/helpers/geocoders_helper.rb
module GeocodersHelper
end

Ac/app/helpers/rooms_helper.rb
module RoomsHelper
end

Ac/app/views/geocoders/_form.html.erb
<%= form_with(model: geocoder, local: true) do |form| %>
  <% if geocoder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(geocoder.errors.count, "error") %> prohibited this geocoder from being saved:</h2>

      <ul>
      <% geocoder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :geocoder_address %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :geocoder_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :geocoder_longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Ac/app/views/geocoders/edit.html.erb
<h1>Editing Geocoder</h1>

<%= render 'form', geocoder: @geocoder %>

<%= link_to 'Show', @geocoder %> |
<%= link_to 'Back', geocoders_path %>

Ac/app/views/geocoders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Geocoders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @geocoders.each do |geocoder| %>
      <tr>
        <td><%= geocoder.address %></td>
        <td><%= geocoder.latitude %></td>
        <td><%= geocoder.longitude %></td>
        <td><%= link_to 'Show', geocoder %></td>
        <td><%= link_to 'Edit', edit_geocoder_path(geocoder) %></td>
        <td><%= link_to 'Destroy', geocoder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Geocoder', new_geocoder_path %>

Ac/app/views/geocoders/new.html.erb
<h1>New Geocoder</h1>

<%= render 'form', geocoder: @geocoder %>

<%= link_to 'Back', geocoders_path %>

Ac/app/views/geocoders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @geocoder.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @geocoder.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @geocoder.longitude %>
</p>

<%= link_to 'Edit', edit_geocoder_path(@geocoder) %> |
<%= link_to 'Back', geocoders_path %>