location/config/routes.rb
Rails.application.routes.draw do
  resources :loactions
  root 'loactions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

location/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

location/app/models/loaction.rb
class Loaction < ApplicationRecord
 
 geocoded_by :address 
 after_validation :geocoded, :if => :address_changed?
end

location/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

location/app/controllers/loactions_controller.rb
class LoactionsController < ApplicationController
  before_action :set_loaction, only: [:show, :edit, :update, :destroy]

  # GET /loactions
  # GET /loactions.json
  def index
    @loactions = Loaction.all
  end

  # GET /loactions/1
  # GET /loactions/1.json
  def show
  end

  # GET /loactions/new
  def new
    @loaction = Loaction.new
  end

  # GET /loactions/1/edit
  def edit
  end

  # POST /loactions
  # POST /loactions.json
  def create
    @loaction = Loaction.new(loaction_params)

    respond_to do |format|
      if @loaction.save
        format.html { redirect_to @loaction, notice: 'Loaction was successfully created.' }
        format.json { render :show, status: :created, location: @loaction }
      else
        format.html { render :new }
        format.json { render json: @loaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loactions/1
  # PATCH/PUT /loactions/1.json
  def update
    respond_to do |format|
      if @loaction.update(loaction_params)
        format.html { redirect_to @loaction, notice: 'Loaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @loaction }
      else
        format.html { render :edit }
        format.json { render json: @loaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loactions/1
  # DELETE /loactions/1.json
  def destroy
    @loaction.destroy
    respond_to do |format|
      format.html { redirect_to loactions_url, notice: 'Loaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loaction
      @loaction = Loaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loaction_params
      params.require(:loaction).permit(:address, :latitude, :longitude)
    end
end

location/app/helpers/application_helper.rb
module ApplicationHelper
end

location/app/helpers/loactions_helper.rb
module LoactionsHelper
end

location/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Location</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

location/app/views/loactions/_form.html.erb
<%= form_with(model: loaction, local: true) do |form| %>
  <% if loaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loaction.errors.count, "error") %> prohibited this loaction from being saved:</h2>

      <ul>
      <% loaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :loaction_address %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :loaction_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :loaction_longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

location/app/views/loactions/edit.html.erb
<h1>Editing Loaction</h1>

<%= render 'form', loaction: @loaction %>

<%= link_to 'Show', @loaction %> |
<%= link_to 'Back', loactions_path %>

location/app/views/loactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loactions</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loactions.each do |loaction| %>
      <tr>
        <td><%= loaction.address %></td>
        <td><%= loaction.latitude %></td>
        <td><%= loaction.longitude %></td>
        <td><%= link_to 'Show', loaction %></td>
        <td><%= link_to 'Edit', edit_loaction_path(loaction) %></td>
        <td><%= link_to 'Destroy', loaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loaction', new_loaction_path %>

location/app/views/loactions/new.html.erb
<h1>New Loaction</h1>

<%= render 'form', loaction: @loaction %>

<%= link_to 'Back', loactions_path %>

location/app/views/loactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @loaction.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @loaction.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @loaction.longitude %>
</p>







<%= link_to 'Edit', edit_loaction_path(@loaction) %> |
<%= link_to 'Back', loactions_path %>