Bank_app/config/routes.rb
Rails.application.routes.draw do
  

  root 'pages#index'
   resources :bank_accounts, only: [:index, :show]

    namespace :api do
      namespace :v1 do
       post "bank_accounts/transaction", to: "bank_accounts#transaction"
      end
    end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Bank_app/app/models/account_transaction.rb
class AccountTransaction < ApplicationRecord
  belongs_to :bank_account

  TRANSACTION = ["withdraw","deposit"]
  
  validates :bank_account, presence: true
  validates :transaction ,presence: true,inclusion: {in: TRANSACTION}
  validates :amount, presence: true, numericality: true
  validates :transction_number ,presence: true,uniqueness: true

  before_validation :load_defaults

  def load_defaults
   if self.new_record?
   	  self.transction_number = SecureRandom.uiid
   end
  end

end

Bank_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bank_app/app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :client
  has_many  :account_transaction
  validates :client ,presence: true 
  validates :account_number, presence: true,uniqueness: true
  validates :balance , presence: true ,numericality: true

  before_validation :load_defaults

  def load_defaults
   if self.new_record?
   	  self.balance = 0.00
   end
  end

  def to_s
   account_number
  end
end

Bank_app/app/models/client.rb
class Client < ApplicationRecord
 has_many  :bank_accounts	
 
 validates :first_name, presence: true
 validates :last_name, presence: true
 validates :middle_name, presence: true
 validates :client_number, presence: true,uniqueness: true

 before_save :format_name

  def to_s
	 "#{first_name}, #{last_name}, #{middle_name}"
	end

	def format_name
	 self.first_name   = self.first_name.upcase
	 self.last_name    = self.last_name.upcase
	 self.middle_name  = self.middle_name.upcase	
	end
end

Bank_app/app/controllers/api/v1/bank_accounts_controller.rb
module Api 
  module V1 
 	class BankAccountsController < ApplicationContoller
        def transaction
          amount = prams[:amount]
          transaction = params[:transaction]
          bank_account_id = prams[:bank_account_id]

          errors =::BankAccounts::ValidNewTranscation.new(
                    amount = amount
                    transaction = transaction
                    bank_account_id = bank_account_id
                    )execute!
          if errors.size > 0
          	render json:{errors: errors},staus: 402
          else
          	 errors =::BankAccounts::PerformTransaction.new(
                    amount: @amount
                    transaction: @transaction
                    bank_account_id: @bank_account_id
                    )execute!
          	 render json: {balance: bank_account.balance}
          	end
          end

        end
  	end
 end
end

Bank_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Bank_app/app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  def index
   @bank_accounts = BankAccount.all
  end

  def show
  	@bank_account = BankAccount.find(params[:id])
  end

 

end

Bank_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

Bank_app/app/helpers/application_helper.rb
module ApplicationHelper
 def number_of_accounts
  BankAccount.count
 end
 def number_of_clients
  Client.count
 end

end

Bank_app/app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

Bank_app/app/helpers/pages_helper.rb
module PagesHelper
end

Bank_app/app/views/bank_accounts/index.html.haml
%h1
  BankAccount
%table.table.table-bordered
  %thead
    %tr
      %th Account number
      %th Blance
      %th Actions
  %tbody
    - @bank_accounts.each do |bank|
      %tr
        %td #{bank.account_number}
        %td #{number_to_currency(bank.balance,unit: "P")}
        %td
          = link_to bank_account_path(bank),class: "btn btn-primary"  do
            show

Bank_app/app/views/bank_accounts/show.html.haml
%h1
  Account Number: #{@bank_account.account_number}


  %small
    #{@bank_account.client.first_name} #{@bank_account.client.last_name}

= button_tag :transaction, id: "btn_transaction" ,class: "btn btn-primary" do 
  NewTransactions	
 
%table.table.table-bordered
  %thead
    %tr
      %th Date of Transction
      %th Transction type
      %th Amount
  %tbody
    - @bank_account.account_transaction.each do |t|
      %tr
        %td #{t.created_at}
        %td #{t.transction}
        %td #{number_to_currency(t.balance,unit: "P")} 
    %tr
      %th 
      %th Balance
      %th #{number_to_currency(@bank_account.balance,unit: "P")} 
#parameters{ data: { bank_account_id: @bank_account.id } }
#modal-transaction.modal.fade.modal-fade
  .modal-dialog
    .modal-content
      .modal-header
        .row
          .col-md-12
            %h2
              NewTranscations 
        %button.close{type:'button', data:{dismiss:'modal'}}
          %span{aria:{hidden:'true'}}
            %i.fa.fa-close
          %span.sr-only Close
        %h4.modal-title
      .modal-body
        .row
          .col-md-12
            .notification
        .row
          .col-md-6
            %lable
              Amount
            = text_field_tag :amount, 0.00, id: "input_amount" ,class: "form-control"  
          .col-md-6
            %lable
              TranscationType
            = select_tag :transction,options_for_select(AccountTransaction::TRANSACTION),id: "select_transaction_type",class: "form-control"  
        %p
      .modal-footer
        %button#btn-close.btn.btn-default{ type: "button" } Close
        
        %button#btn-save.btn.btn-primary{type:'button'} save

  
= javascript_include_tag "bank_accounts/show"
:javascript
  $(document).ready(function(){
    show.init();
  });
	  