geocoder/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places, except: [:update, :edit, :destroy]
  resources :distances, only: [:new, :create]

  root 'places#index'
end

geocoder/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

geocoder/app/models/place.rb
class Place < ApplicationRecord
	
	attr_accessor :address

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude

  after_validation -> {
    self.address = self.address
    geocode
  }, if: ->(obj){ obj.address.present? and obj.address != obj.address }

  after_validation :reverse_geocode, unless: ->(obj) { obj.address.present? },
                   if: ->(obj){ obj.latitude.present? and obj.latitude_changed? and obj.longitude.present? and obj.longitude_changed? }


end

geocoder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

geocoder/app/controllers/distances_controller.rb
class DistancesController < ApplicationController
end

geocoder/app/controllers/places_controller.rb
class PlacesController < ApplicationController
 

 def index
    @places = Place.order('created_at DESC')
  end

  def show
    @place = Place.find(params[:id])
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = "Place added!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

    def place_params
      params.require(:place).permit(:title, :address, :latitude, :longitude, :visited_by)
    end
end

geocoder/app/helpers/application_helper.rb
module ApplicationHelper
end

geocoder/app/helpers/distances_helper.rb
module DistancesHelper
end

geocoder/app/helpers/places_helper.rb
module PlacesHelper
end

geocoder/app/views/distances/new.html.erb
<header><h1 class="display-4">Measure Distance</h1></header>


<%= form_tag distances_path do %>
	  <fieldset class="form-group">
		  <%= label_tag 'from', 'From' %>
		  <%= select_tag 'from', options_from_collection_for_select(@places, :id, :title), class: "form-control" %>
		</fieldset>

	  <fieldset class="form-group">
		  <%= label_tag 'to', 'To' %>
		  <%= select_tag 'to', options_from_collection_for_select(@places, :id, :title), class: "form-control" %>
	</fieldset>

 	 <%= submit_tag 'Go!', class: 'btn btn-primary' %>
<% end %>